#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

. `dirname $0`/bigtop.bom

export GOPATH=$(pwd)
export PATH="${GOPATH}/bin:$PATH"
mkdir -p src/github.com/greenplum-db
ls | grep -v src | xargs mv -t src/github.com/greenplum-db
#mv !(src) src/github.com/greenplum-db
cd src/github.com/greenplum-db
#sed -i 's/MINIMUM_GPDB5_VERSION = "5.1.0"/MINIMUM_GPDB5_VERSION = "5.0.0"/' utils/util.go
#sed -i 's/@$(MAKE) install_helper/#@$(MAKE) install_helper/' Makefile
       
make depend
make build